import React from 'react';
import { ArrowLeftIcon } from './IconComponents';

interface LegalPageProps {
  onBack: () => void;
}

export const TermsOfService: React.FC<LegalPageProps> = ({ onBack }) => (
    <div className="max-w-4xl mx-auto animate-fade-in text-left">
        <button onClick={onBack} className="flex items-center gap-2 text-sm font-medium text-slate-300 hover:text-white transition-colors mb-8">
            <ArrowLeftIcon className="h-4 w-4" />
            Back to App
        </button>
        <div className="bg-slate-900/60 backdrop-blur-xl border border-slate-800 p-8 rounded-2xl shadow-lg">
            <div className="prose-dark max-w-none">
                <h1>Terms of Service</h1>
                <p>Last updated: August 1, 2024</p>

                <h2>1. Agreement to Terms</h2>
                <p>By accessing and using the GitHub Project Analyzer (the "Service"), you agree to be bound by these Terms of Service ("Terms"). This Service is provided for educational and demonstrational purposes only. If you do not agree to these Terms, you are prohibited from using the Service.</p>

                <h2>2. Description of Service</h2>
                <p>The Service allows users to input a public GitHub repository URL and receive an AI-generated analysis of that repository. To use the Service, you must provide your own API key for the Google Gemini API. The Service also utilizes the public GitHub API.</p>

                <h2>3. User Responsibilities</h2>
                <ul>
                    <li>You are responsible for obtaining and securing your own API Key from Google.</li>
                    <li>You are responsible for all activities that occur under your API Key. You agree not to share your API Key with others.</li>
                    <li>You agree to comply with the terms of service of any third-party services used by this application, including those of Google and GitHub.</li>
                    <li>You agree not to use the Service for any illegal or unauthorized purpose.</li>
                </ul>

                <h2>4. Intellectual Property Rights</h2>
                <p>The Service and its original content, features, and functionality are and will remain the exclusive property of the developer. The Service is protected by copyright, trademark, and other laws. Our trademarks may not be used in connection with any product or service without the prior written consent of the developer.</p>

                <h2>5. Disclaimers</h2>
                <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. Your use of the Service is at your sole risk. The Service is for educational purposes only and we make no warranties or representations about the accuracy, reliability, or completeness of the content generated by the AI.</p>
                <p>We do not warrant that a) the Service will function uninterrupted, secure, or available at any particular time or location; b) any errors or defects will be corrected; c) the results of using the Service will meet your requirements.</p>

                <h2>6. Limitation of Liability</h2>
                <p>In no event shall the developer, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>

                <h2>7. Termination</h2>
                <p>We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>

                <h2>8. Governing Law</h2>
                <p>These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which the developer resides, without regard to its conflict of law provisions.</p>
                
                <h2>9. Changes to Terms</h2>
                <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by updating the "Last updated" date of these Terms.</p>
            </div>
        </div>
    </div>
);
